pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t flask-hello ./TW2/Task1-Docker-Compose'
            }
        }

    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
    }
}